version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-commerce
    environment:
      - MYSQL_USER=commerce
      - MYSQL_PASSWORD=commerce
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=commerce
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --init-connect=SET NAMES utf8mb4 COLLATE utf8mb4_general_ci
      - --character-set-client-handshake=FALSE
    restart: always
    volumes:
      - mysql-volume:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-commerce
    ports:
      - "6380:6379"
    volumes:
      - ./redis/data:/data
    command:
      - redis-server
    restart: always

  localstack:
    image: localstack/localstack:latest
    container_name: localstack-commerce
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      - SERVICES=sqs           # SQS만 활성화
      - DEBUG=1                # 디버그 로그 활성화
      - PERSISTENCE=1          # 재시작 시 데이터 유지
      - AWS_DEFAULT_REGION=ap-northeast-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./localstack/init:/etc/localstack/init/ready.d"  # 초기화 스크립트
    restart: always

volumes:
  mysql-volume: