spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/commerce?connectionCollation=utf8mb4_general_ci&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: commerce
    password: commerce

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: Asia/Seoul
    open-in-view: false
    show-sql: false

  data:
    redis:
      host: localhost
      port: 6380

  security:
    jwt:
      secret-key: "+pI6fxTOdlPIAxaDPR30kfudnkjBkS25lD69kEZNv6iSzdv0ve1ChHj3fpSkIbwWtvq68lGjTtXFrIoGgxVCaQ=="
      access-ttl-seconds: 3600 # 1시간
      refresh-ttl-seconds: 86400 # 24시간

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
    sqs:
      endpoint: http://localhost:4566  # LocalStack 엔드포인트
    stack:
      auto: false

app:
  aws:
    bucket: ${AWS_BUCKET_NAME}
    region: ${AWS_REGION:ap-northeast-2}
  queue:
    sqs: http://sqs.ap-northeast-2.localhost.localstack.cloud:4566/000000000000/sqs-commerce
    dlq: http://sqs.ap-northeast-2.localhost.localstack.cloud:4566/000000000000/dlq-commerce